export type CSSVariables =
  | 'white'
  | 'black'
  | 'text_primary'
  | 'text_secondary'
  | 'text_tertiary'
  | 'text_disable'
  | 'text_inverted'
  | 'special_red'
  | 'special_orange'
  | 'special_green'
  | 'special_blue'
  | 'special_blue_bg1'
  | 'special_red_bg1'
  | 'special_red_bg2'
  | 'special_green_bg'
  | 'special_green_bg1'
  | 'special_green_bg2'
  | 'special_orange_bg1'
  | 'special_orange_bg2'
  | 'special_purple'
  | 'special_purple_bg1'
  | 'special_orange_bg3'
  | 'special_green_bg3'
  | 'special_red_bg3'
  | 'bg_hide'
  | 'neutral_10'
  | 'neutral_20'
  | 'neutral_25'
  | 'neutral_30'
  | 'neutral_40'
  | 'neutral_50'
  | 'neutral_60'
  | 'neutral_70'
  | 'neutral_80'
  | 'neutral_90'
  | 'neutral_100'
  | 'border_primary'
  | 'border_secondary'
  | 'border_active'
  | 'el_active_default'
  | 'el_active_hover'
  | 'el_active_pressed'
  | 'el_active_disabled'
  | 'el_active_color_inside'
  | 'el_active_disabled_color_inside'
  | 'el_inactive_default'
  | 'el_inactive_hover'
  | 'el_inactive_pressed'
  | 'el_inactive_disabled'
  | 'el_inactive_color_inside'
  | 'el_inactive_disabled_color_inside'
  | 'modal_primary'
  | 'modal_bg'
  | 'select_default'
  | 'select_hover'
  | 'select_item'
  | 'select_item_hover'
  | 'select_border'
  | 'block_bg'
  | 'block_bg_cards'
  | 'block_bg_cards_hover'
  | 'block_bg_cards_item'
  | 'block_bg_cards_hover_item'
  | 'block_btn'
  | 'block_btn_item'
  | 'block_btn_hover'
  | 'block_btn_item_hover'
  | 'block_payform'
  | 'blog_gr'
  | 'blog_gr_rtl'
  | 'block_gr'
  | 'block_gr_rtl'
  | 'bg_buttonUp'
  | 'table_bg'
  | 'table_items'
  | 'table_hover_stroke'
  | 'table_hover_items'
  | 'table_action_btn'
  | 'table_action_btn_hover'
  | 'table_icon_default'
  | 'table_icon_hover'
  | 'footer_bg'
  | 'footer_btn'
  | 'footer_btn_hover'
  | 'footer_tab_bar'
  | 'footer_tab_bar_shadow'
  | 'block_shadow'
  | 'selected_shadow'
  | 'modal_shadow'
  | 'cards_shadow'
  | 'tooltip_shadow'
  | 'toggle_shadow'
  | 'subheader_bg'
  | 'bg_primary'
  | 'button_primary'
  | 'gray'
  | 'black_gray';

export const CSS_VARIABLES_META: { [key in CSSVariables]: string } = {
  black_gray: 'var(--black_gray)',
  gray: 'var(--gray)',
  bg_hide: 'var(--bg_hide)',
  black: 'var(--black)',
  border_active: 'var(--border_active)',
  border_primary: 'var(--border_primary)',
  border_secondary: 'var(--border_secondary)',
  el_active_color_inside: 'var(--el_active_color_inside)',
  el_active_default: 'var(--el_active_default)',
  el_active_disabled: 'var(--el_active_disabled)',
  el_active_disabled_color_inside: 'var(--el_active_disabled_color_inside)',
  el_active_hover: 'var(--el_active_hover)',
  el_active_pressed: 'var(--el_active_pressed)',
  el_inactive_color_inside: 'var(--el_inactive_color_inside)',
  el_inactive_default: 'var(--el_inactive_default)',
  neutral_10: 'var(--neutral_10)',
  block_bg: 'var(--block_bg)',
  neutral_100: 'var(--neutral_100)',
  block_bg_cards: 'var(--block_bg_cards)',
  neutral_20: 'var(--neutral_20)',
  block_bg_cards_hover: 'var(--block_bg_cards_hover)',
  neutral_25: 'var(--neutral_25)',
  block_bg_cards_hover_item: 'var(--block_bg_cards_hover_item)',
  neutral_30: 'var(--neutral_30)',
  block_bg_cards_item: 'var(--block_bg_cards_item)',
  neutral_40: 'var(--neutral_40)',
  block_btn: 'var(--block_btn)',
  special_blue: 'var(--special_blue)',
  block_btn_hover: 'var(--block_btn_hover)',
  special_blue_bg1: 'var(--special_blue_bg1)',
  bg_buttonUp: 'var(--bg_buttonUp)',
  special_green: 'var(--special_green)',
  block_btn_item: 'var(--block_btn_item)',
  special_green_bg: 'var(--special_green_bg)',
  block_btn_item_hover: 'var(--block_btn_item_hover)',
  special_green_bg1: 'var(--special_green_bg1)',
  block_gr: 'var(--block_gr)',
  special_green_bg2: 'var(--special_green_bg2)',
  block_gr_rtl: 'var(--block_gr_rtl)',
  special_green_bg3: 'var(--special_green_bg3)',
  block_payform: 'var(--block_payform)',
  special_orange: 'var(--special_orange)',
  blog_gr: 'var(--blog_gr)',
  special_orange_bg1: 'var(--special_orange_bg1)',
  block_shadow: 'var(--block_shadow)',
  special_red: 'var(--special_red)',
  blog_gr_rtl: 'var(--blog_gr_rtl)',
  text_disable: 'var(--text_disable)',
  cards_shadow: 'var(--cards_shadow)',
  text_primary: 'var(--text_primary)',
  bg_primary: 'var(--bg_primary)',
  white: 'var(--white)',
  el_inactive_disabled: 'var(--el_inactive_disabled)',
  el_inactive_disabled_color_inside: 'var(--el_inactive_disabled_color_inside)',
  text_secondary: 'var(--text_secondary)',
  el_inactive_hover: 'var(--el_inactive_hover)',
  text_tertiary: 'var(--text_tertiary)',
  el_inactive_pressed: 'var(--el_inactive_pressed)',
  text_inverted: 'var(--text_inverted)',
  footer_bg: 'var(--footer_bg)',
  footer_btn: 'var(--footer_btn)',
  special_orange_bg2: 'var(--special_orange_bg2)',
  footer_btn_hover: 'var(--footer_btn_hover)',
  special_red_bg1: 'var(--special_red_bg1)',
  footer_tab_bar: 'var(--footer_tab_bar)',
  special_red_bg2: 'var(--special_red_bg2)',
  footer_tab_bar_shadow: 'var(--footer_tab_bar_shadow)',
  modal_bg: 'var(--modal_bg)',
  special_orange_bg3: 'var(--special_orange_bg3)',
  modal_primary: 'var(--modal_primary)',
  special_purple: 'var(--special_purple)',
  modal_shadow: 'var(--modal_shadow)',
  special_purple_bg1: 'var(--special_purple_bg1)',
  neutral_50: 'var(--neutral_50)',
  neutral_60: 'var(--neutral_60)',
  special_red_bg3: 'var(--special_red_bg3)',
  neutral_70: 'var(--neutral_70)',
  neutral_80: 'var(--neutral_80)',
  neutral_90: 'var(--neutral_90)',
  select_border: 'var(--select_border)',
  select_default: 'var(--select_default)',
  select_hover: 'var(--select_hover)',
  select_item: 'var(--select_item)',
  select_item_hover: 'var(--select_item_hover)',
  selected_shadow: 'var(--selected_shadow)',
  subheader_bg: 'var(--subheader_bg)',
  table_action_btn: 'var(--table_action_btn)',
  table_action_btn_hover: 'var(--table_action_btn_hover)',
  table_bg: 'var(--table_bg)',
  table_hover_items: 'var(--table_hover_items)',
  table_hover_stroke: 'var(--table_hover_stroke)',
  table_icon_default: 'var(--table_icon_default)',
  table_icon_hover: 'var(--table_icon_hover)',
  table_items: 'var(--table_items)',
  toggle_shadow: 'var(--toggle_shadow)',
  tooltip_shadow: 'var(--tooltip_shadow)',
  button_primary: 'var(--button_primary)',
};
